// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_api.Data;

#nullable disable

namespace backend_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend_api.Models.Answer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerID"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("AnswerID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("backend_api.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("backend_api.Models.ExamBlueprint", b =>
                {
                    b.Property<int>("BlueprintID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlueprintID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("LicenseTypeID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.HasKey("BlueprintID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LicenseTypeID", "CategoryID")
                        .IsUnique()
                        .HasDatabaseName("UC_License_Category");

                    b.ToTable("ExamBlueprints");
                });

            modelBuilder.Entity("backend_api.Models.ExamSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasCriticalError")
                        .HasColumnType("bit");

                    b.Property<int>("LicenseTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.HasIndex("LicenseTypeID");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("backend_api.Models.LicenseType", b =>
                {
                    b.Property<int>("LicenseTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseTypeID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassingScore")
                        .HasColumnType("int");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseTypeID");

                    b.ToTable("LicenseTypes");
                });

            modelBuilder.Entity("backend_api.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<int?>("RegulationID")
                        .HasColumnType("int");

                    b.Property<int?>("SignID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("RegulationID");

                    b.HasIndex("SignID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("backend_api.Models.QuestionLicenseMap", b =>
                {
                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("LicenseTypeID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID", "LicenseTypeID");

                    b.ToTable("QuestionLicenseMaps");
                });

            modelBuilder.Entity("backend_api.Models.Regulation", b =>
                {
                    b.Property<int>("RegulationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegulationID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PenaltyRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegulationID");

                    b.ToTable("Regulations");
                });

            modelBuilder.Entity("backend_api.Models.SampleExam", b =>
                {
                    b.Property<int>("SampleExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SampleExamID"));

                    b.Property<string>("ExamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LicenseTypeID")
                        .HasColumnType("int");

                    b.HasKey("SampleExamID");

                    b.HasIndex("LicenseTypeID");

                    b.ToTable("SampleExams");
                });

            modelBuilder.Entity("backend_api.Models.SampleExamDetail", b =>
                {
                    b.Property<int>("SampleExamID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("SampleExamID", "QuestionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("SampleExamDetails");
                });

            modelBuilder.Entity("backend_api.Models.SessionDetail", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailID"));

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedAnswerID")
                        .HasColumnType("int");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.HasKey("DetailID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SelectedAnswerID");

                    b.HasIndex("SessionID");

                    b.ToTable("SessionDetails");
                });

            modelBuilder.Entity("backend_api.Models.TrafficSign", b =>
                {
                    b.Property<int>("SignID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SignID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SignID");

                    b.ToTable("TrafficSigns");
                });

            modelBuilder.Entity("backend_api.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AvatarURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend_api.Models.WrongAnswerLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAttempted")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("UserID", "QuestionID")
                        .IsUnique()
                        .HasDatabaseName("UC_User_Question");

                    b.ToTable("WrongAnswerLogs");
                });

            modelBuilder.Entity("backend_api.Models.Answer", b =>
                {
                    b.HasOne("backend_api.Models.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_api.Models.ExamBlueprint", b =>
                {
                    b.HasOne("backend_api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend_api.Models.LicenseType", "LicenseType")
                        .WithMany()
                        .HasForeignKey("LicenseTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("LicenseType");
                });

            modelBuilder.Entity("backend_api.Models.ExamSession", b =>
                {
                    b.HasOne("backend_api.Models.LicenseType", "LicenseType")
                        .WithMany()
                        .HasForeignKey("LicenseTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LicenseType");
                });

            modelBuilder.Entity("backend_api.Models.Question", b =>
                {
                    b.HasOne("backend_api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend_api.Models.Regulation", "Regulation")
                        .WithMany()
                        .HasForeignKey("RegulationID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backend_api.Models.TrafficSign", "TrafficSign")
                        .WithMany()
                        .HasForeignKey("SignID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Regulation");

                    b.Navigation("TrafficSign");
                });

            modelBuilder.Entity("backend_api.Models.QuestionLicenseMap", b =>
                {
                    b.HasOne("backend_api.Models.Question", null)
                        .WithMany("QuestionLicenseMaps")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_api.Models.SampleExam", b =>
                {
                    b.HasOne("backend_api.Models.LicenseType", "LicenseType")
                        .WithMany()
                        .HasForeignKey("LicenseTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LicenseType");
                });

            modelBuilder.Entity("backend_api.Models.SampleExamDetail", b =>
                {
                    b.HasOne("backend_api.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend_api.Models.SampleExam", null)
                        .WithMany("SampleExamDetails")
                        .HasForeignKey("SampleExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("backend_api.Models.SessionDetail", b =>
                {
                    b.HasOne("backend_api.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend_api.Models.Answer", "SelectedAnswer")
                        .WithMany()
                        .HasForeignKey("SelectedAnswerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backend_api.Models.ExamSession", null)
                        .WithMany("SessionDetails")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelectedAnswer");
                });

            modelBuilder.Entity("backend_api.Models.WrongAnswerLog", b =>
                {
                    b.HasOne("backend_api.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("backend_api.Models.ExamSession", b =>
                {
                    b.Navigation("SessionDetails");
                });

            modelBuilder.Entity("backend_api.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("QuestionLicenseMaps");
                });

            modelBuilder.Entity("backend_api.Models.SampleExam", b =>
                {
                    b.Navigation("SampleExamDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
